### ISSUE TITLE
[Request] Mac OS X support

### ISSUE THREAD

**Issue by chrisidefix** [amol9/vlc-ctrl#1]
Any idea if this could also work on OS X (it doesn't right now)? I am not familiar with dbus or the other requirements used, so my question is more conceptual.

I did try it on Mac OS X, but got the error below:
(I am using VLC 2.2.2 - should that technically be working?)

```
Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
org.freedesktop.DBus.Error.NoMemory: Not enough memory
Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
org.freedesktop.DBus.Error.NoMemory: Not enough memory
Traceback (most recent call last):
  File "~/Library/Python/2.7/bin/vlc-ctrl", line 11, in <module>
    sys.exit(main())
  File "~/Library/Python/2.7/lib/python/site-packages/vlc_ctrl/main.py", line 19, in main
    commandline.execute()
  File "~/Library/Python/2.7/lib/python/site-packages/redcmd/commandline.py", line 50, in execute
    self._command_collection.execute(args, namespace)
  File "~/Library/Python/2.7/lib/python/site-packages/redcmd/command_collection.py", line 465, in execute
    cmd_func.execute(args)
  File "~/Library/Python/2.7/lib/python/site-packages/redcmd/cmdfunc.py", line 21, in execute
    return self.func(*self.get_arg_list(self.func, args))
  File "~/Library/Python/2.7/lib/python/site-packages/vlc_ctrl/client.py", line 35, in play
    self._players.play(path, filter)
  File "~/Library/Python/2.7/lib/python/site-packages/vlc_ctrl/player_list.py", line 38, in wrapped
    self._list[0].get_dbus_interface()
  File "~/Library/Python/2.7/lib/python/site-packages/vlc_ctrl/player.py", line 54, in get_bus_interface
    raise PlayerError('vlc is not running')
vlc_ctrl.player.PlayerError: vlc is not running
```

**Comment by amol9** [comment]
Currently, it is not supported on Mac. I don't have a mac, so, did not really prioritize it.
I have used dbus for communicating with vlc player which is available on Linux.

I am planning on supporting WIndows, for which I'll have to communicate with vlc using its web interface / telnet interface. Once, that is done, technically, it should work on Mac as well.
